services:

  node_exporter:
    image: /prom/node-exporter:v1.8.2
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "500M"

  cadvisor:
    image: /hosseinasgari/cadvisor-health:latest
    container_name: cadvisor1
    restart: unless-stopped
    entrypoint: sh /code/run.sh
    volumes:
      - '/:/rootfs:ro,rslave'
      - '/var/run:/var/run:ro'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro,rslave'
    network_mode: "host"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "1G"

