{
 "title": "Docker-cAdvisor",
 "description": "cAdvisor with node selection",
 "tags": [
  "docker",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(container_cpu_user_seconds_total, job)"
   },
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(container_memory_cache,name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(container_cpu_user_seconds_total{name=~\"$name\"}, instance)"
   },
   {
    "name": "interface",
    "label": "interface",
    "query": "label_values(container_network_receive_bytes_total{name=~\"$name\",instance=~\"$instance\"}, interface)"
   },
   {
    "name": "sum_without",
    "label": "sum",
    "query": "unsum,instance,image,container_label_restartcount,device"
   }
  ]
 },
 "panels": [
  {
   "title": "container_status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_status{instance=~\"$instance\",container_name=~\".+\",container_name!=\"blackbox-iranianasnaf-init-script-iranianasnaf-1\",container_name!=\"blackbox-ersalpishnevis-init-script-ersalpishnevis-1\",container_name!=\"blackbox-post-init-script-post-1\",container_name!=\"python\",container_name!=\"contract-backend-rent-pdf-new-1\",container_name!=\"19a1725aa06b_rent-api-3\",container_name!=\"50ef14b593ed_rent-api-2\",container_name!=\"3cea88d84219_rent-api-0\",container_name!=\"eb9f5cc9f5ed_rent-api-1\"}",
     "legendFormat": "ip={{instance}},name={{container_name}}"
    }
   ]
  },
  {
   "title": "container_health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_health_status{instance=~\"$instance\",container_name=~\".+\",container_name!=\"cadvisor1\",container_name!=\"19a1725aa06b_rent-api-3\",container_name!=\"50ef14b593ed_rent-api-2\",container_name!=\"3cea88d84219_rent-api-0\",container_name!=\"eb9f5cc9f5ed_rent-api-1\"}",
     "legendFormat": "ip={{instance}},name={{container_name}}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node list",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_cpu_cores{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_cpu_user_seconds_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]) * 100)by (instance) / sum(machine_cpu_cores{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "((sum(container_memory_usage_bytes{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance) - sum(container_memory_cache{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance)) / sum(machine_memory_bytes{instance=~\"$instance\"}) by (instance)) * 100"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance) - sum(container_memory_cache{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance)"
    },
    {
     "expr": "sum(machine_memory_bytes{instance=~\"$instance\"}) by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_reads_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_fs_writes_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\"}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",interface=\"$interface\"}[5m]))by (instance)"
    },
    {
     "expr": "sum(irate(container_network_receive_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",interface=\"$interface\"}[5m]))by (instance)"
    }
   ]
  },
  {
   "title": "$name",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(irate(container_cpu_usage_seconds_total{instance=~\"$instance\",name=~\"$name\",instance=~\"172.16.71.206:6677\",image!=\"\"}[5m]) * 100)by (instance,name))  /16\r\nor\r\n(sum(irate(container_cpu_usage_seconds_total{instance=~\"$instance\",name=~\"$name\",instance=~\"172.16.71.194:6677|172.16.111.2:6677|172.16.111.6:6677|172.16.111.5:6677|172.16.111.3:6677\",image!=\"\"}[5m]) * 100)by (instance,name))  /64\r\nor\r\n(sum(irate(container_cpu_usage_seconds_total{instance=~\"$instance\",name=~\"$name\",instance=~\"172.16.71.203:6677|172.16.74.116:6677|172.16.71.199:6677|172.16.71.200:6677|172.16.71.196:6677|172.16.71.198:6677|172.16.71.197:6677|172.16.71.195:6677|172.16.74.115:6677|172.16.74.114:6677\",image!=\"\"}[5m]) * 100)by (instance,name))  /32",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum(container_memory_usage_bytes{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance,name) - sum(container_memory_cache{name=~\"$name\",instance=~\"$instance\",image!=\"\"}) by (instance,name))  / (33690087424)) * 100 \r\nor \r\n((sum(container_memory_usage_bytes{name=~\"$name\",instance=\"172.16.111.5:6666\",image!=\"\"}) by (instance,name) - sum(container_memory_cache{name=~\"$name\",instance=\"172.16.111.5:6666\",image!=\"\"}) by (instance,name))  / (66690087424)) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "I/O Tx:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_fs_writes_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
     "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "I/O Rx:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_fs_reads_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",device!~\"/dev/dm.*\"}[5m]))",
     "legendFormat": "{{name}}: device=\"{{device}}\", instance=\"{{instance}}\""
    }
   ]
  },
  {
   "title": "Network Tx:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_network_transmit_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",interface=\"$interface\"}[5m])) ",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Rx:sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum without (dc,from,id,${sum_without:csv}) (irate(container_network_receive_bytes_total{name=~\"$name\",instance=~\"$instance\",image!=\"\",interface=\"$interface\"}[5m]))",
     "legendFormat": "{{name}}: {{instance}}"
    }
   ]
  }
 ]
}