{
 "title": "service-check",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": " ______________________________________________________________________________________________________________  (قدیم) سرویس پست _____________________________________________________________________________________________________________",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "سرویس پست (قدیم)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://sr-tuix.mrud.ir/Services/PostAPI/AddressByPostcode\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "میانگین زمان پاسخ سرویس پست (قدیم)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ثانیه" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"https://sr-tuix.mrud.ir/Services/PostAPI/AddressByPostcode\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "وضعیت کد های پاسخ سرویس پست (قدیم)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "(count_values(\"code\", probe_http_status_code{instance=\"https://sr-tuix.mrud.ir/Services/PostAPI/AddressByPostcode\"}))  \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"https://sr-tuix.mrud.ir/Services/PostAPI/AddressByPostcode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(probe_duration_seconds{instance=\"https://sr-tuix.mrud.ir/Services/PostAPI/AddressByPostcode\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(probe_duration_seconds{instance=\"https://sr-tuix.mrud.ir/Services/PostAPI/AddressByPostcode\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://sr-tuix.mrud.ir/Services/PostAPI/AddressByPostcode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " __________________________________________________________________________________________________________سرویس ارسال پیش نویس_________________________________________________________________________________________________________",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "سرویس ارسال پیش نویس",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "probe_success{instance=\"https://documentgateway-gateway.apps.lab.notary.ir/DocumentSSAR/v1/VowDocumentService\"} ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "میانگین زمان پاسخ ارسال پیش نویس",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 5, "x": 13, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ثانیه" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(probe_duration_seconds{instance=\"https://documentgateway-gateway.apps.lab.notary.ir/DocumentSSAR/v1/VowDocumentService\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "وضعیت کد های پاسخ سرویس ارسال پیش نویس ",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 18, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "count" ] } },
     "targets": [
      {
       "expr": "(count_values(\"code\", probe_http_status_code{instance=\"https://documentgateway-gateway.apps.lab.notary.ir/DocumentSSAR/v1/VowDocumentService\"}))  \r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "probe_duration_seconds{instance=\"https://documentgateway-gateway.apps.lab.notary.ir/DocumentSSAR/v1/VowDocumentService\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "bargauge",
     "gridPos": { "h": 5, "w": 10, "x": 13, "y": 21 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min_over_time(probe_duration_seconds{instance=\"https://documentgateway-gateway.apps.lab.notary.ir/DocumentSSAR/v1/VowDocumentService\"}[$__range])",
       "legendFormat": "__auto"
      },
      {
       "expr": "max_over_time(probe_duration_seconds{instance=\"https://documentgateway-gateway.apps.lab.notary.ir/DocumentSSAR/v1/VowDocumentService\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 13, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "probe_http_status_code{instance=\"https://documentgateway-gateway.apps.lab.notary.ir/DocumentSSAR/v1/VowDocumentService\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": " ______________________________________________________________________________________________________________  (جدید) سرویس پست _____________________________________________________________________________________________________________",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 }
  },
  {
   "title": "سرویس پست (جدید)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://sr-tuix.mrud.ir/Services/NewPostAPI/AddressByPostcode\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "میانگین زمان پاسخ سرویس پست (جدید)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ثانیه" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"https://sr-tuix.mrud.ir/Services/NewPostAPI/AddressByPostcode\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "وضعیت کد های پاسخ سرویس پست (جدید)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "(count_values(\"code\", probe_http_status_code{instance=\"https://sr-tuix.mrud.ir/Services/NewPostAPI/AddressByPostcode\"}))  \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"https://sr-tuix.mrud.ir/Services/NewPostAPI/AddressByPostcode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(probe_duration_seconds{instance=\"https://sr-tuix.mrud.ir/Services/NewPostAPI/AddressByPostcode\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(probe_duration_seconds{instance=\"https://sr-tuix.mrud.ir/Services/NewPostAPI/AddressByPostcode\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://sr-tuix.mrud.ir/Services/NewPostAPI/AddressByPostcode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ______________________________________________________________________________________________________________سرویس ودیعه _____________________________________________________________________________________________________________",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 }
  },
  {
   "title": "سرویس ودیعه",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://khodnevis.mrud.ir/services/amlak/v2/tracking_code/complete/\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "میانگین زمان پاسخ سرویس ودیعه",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ثانیه" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"https://khodnevis.mrud.ir/services/amlak/v2/tracking_code/complete/\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "وضعیت کد های پاسخ سرویس ودیعه",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "(count_values(\"code\", probe_http_status_code{instance=\"https://khodnevis.mrud.ir/services/amlak/v2/tracking_code/complete/\"}))  \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"https://khodnevis.mrud.ir/services/amlak/v2/tracking_code/complete/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(probe_duration_seconds{instance=\"https://khodnevis.mrud.ir/services/amlak/v2/tracking_code/complete/\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(probe_duration_seconds{instance=\"https://khodnevis.mrud.ir/services/amlak/v2/tracking_code/complete/\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://khodnevis.mrud.ir/services/amlak/v2/tracking_code/complete/\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "____________________________________________________________________________________________________________سرویس ایران اصناف ___________________________________________________________________________________________________________",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 }
  },
  {
   "title": "سرویس ایران اصناف",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://novingw.iranianasnaf.ir/api/v1/service/license/inquiry/main\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "میانگین زمان پاسخ سرویس ایران اصناف",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ثانیه" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"https://novingw.iranianasnaf.ir/api/v1/service/license/inquiry/main\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "وضعیت کد های پاسخ سرویس ایران اصناف",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "(count_values(\"code\", probe_http_status_code{instance=\"https://novingw.iranianasnaf.ir/api/v1/service/license/inquiry/main\"}))  \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"https://novingw.iranianasnaf.ir/api/v1/service/license/inquiry/main\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(probe_duration_seconds{instance=\"https://novingw.iranianasnaf.ir/api/v1/service/license/inquiry/main\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(probe_duration_seconds{instance=\"https://novingw.iranianasnaf.ir/api/v1/service/license/inquiry/main\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://novingw.iranianasnaf.ir/api/v1/service/license/inquiry/main\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ______________________________________________________________________________________________________________سرویس املاک _____________________________________________________________________________________________________________",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }
  },
  {
   "title": "سرویس املاک",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://amlakservice.mrud.ir/api/v1/property-deal/person/property?NationalCode=0481352317\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "میانگین زمان پاسخ سرویس املاک",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "ثانیه" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"https://amlakservice.mrud.ir/api/v1/property-deal/person/property?NationalCode=0481352317\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "وضعیت کد های پاسخ سرویس املاک",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "(count_values(\"code\", probe_http_status_code{instance=\"https://amlakservice.mrud.ir/api/v1/property-deal/person/property?NationalCode=0481352317\"}))  \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"https://amlakservice.mrud.ir/api/v1/property-deal/person/property?NationalCode=0481352317\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(probe_duration_seconds{instance=\"https://amlakservice.mrud.ir/api/v1/property-deal/person/property?NationalCode=0481352317\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(probe_duration_seconds{instance=\"https://amlakservice.mrud.ir/api/v1/property-deal/person/property?NationalCode=0481352317\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 62 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://amlakservice.mrud.ir/api/v1/property-deal/person/property?NationalCode=0481352317\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ______________________________________________________________________________________________________________ سرویس اهملیت  _____________________________________________________________________________________________________________",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 }
  },
  {
   "title": "سرویس اهلیت",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "probe_success{instance=\"https://op1.pgsb.ir/b2b/client/apim/v1/ghoveghazaiye/gwaggregateV9/aggregateV9\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "میانگین زمان پاسخ سرویس اهلیت",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 13, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ثانیه" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"https://op1.pgsb.ir/b2b/client/apim/v1/ghoveghazaiye/gwaggregateV9/aggregateV9\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " وضعیت کد های پاسخ سرویس  اهلیت",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "(count_values(\"code\", probe_http_status_code{instance=\"https://op1.pgsb.ir/b2b/client/apim/v1/ghoveghazaiye/gwaggregateV9/aggregateV9\"}))  \r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=\"https://op1.pgsb.ir/b2b/client/apim/v1/ghoveghazaiye/gwaggregateV9/aggregateV9\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 13, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min_over_time(probe_duration_seconds{instance=\"https://op1.pgsb.ir/b2b/client/apim/v1/ghoveghazaiye/gwaggregateV9/aggregateV9\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "max_over_time(probe_duration_seconds{instance=\"https://new.srem.ir/auth/sso/login/gov/40\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"https://op1.pgsb.ir/b2b/client/apim/v1/ghoveghazaiye/gwaggregateV9/aggregateV9\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}