groups:
- name: cpu_alerts
  rules:
  - alert: cpu_usage_container_80%
    expr: |
      sum(rate(container_cpu_usage_seconds_total{name=~".+"}[1m])) by (name) / sum(container_spec_cpu_quota{name=~".+"} / 100000) by (name) * 100 > 80
#      or
 #     sum(rate(container_cpu_usage_seconds_total{name=~".+"}[1m])) by (name) / sum(container_spec_cpu_period{name=~".+"} / 100000) by (name) * 100 > 80
    for: 5s
    labels: 
      severity: critical
    annotations:
      summary: cpu usage Container "{{ $labels.name }}" is more 80%  
