groups:
- name: ram_alerts
  rules:
    - alert: server_ram_usage_80%
    expr: |
      (1 - (node_memory_MemAvailable_bytes{instance=~".+"} / (node_memory_MemTotal_bytes{instance=~".+"})))* 100 > 80
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: ram usage server "{{ $labels.instance }}" is more 70%




